// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ngvs2022reviews.data.Entities
{
    internal class DatabaseHelper
    {
        internal static readonly string Connection = @"Data Source=.;Initial Catalog=Northwind;Integrated Security=True";
    }
}