// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ngvs2022reviews.data.Entities
{
    public partial class Message
    {
        [Key]
        [Column(TypeName = "numeric(19, 0)")]
        public decimal id { get; set; }
        [Column("message")]
        [StringLength(255)]
        [Unicode(false)]
        public string message1 { get; set; }
    }
}